parameters:
  gatekeeper:
    version: v1
  kapitan:
    compile:
      - name: template-gatekeeper-fluxcd-resources
        input_type: kadet
        input_paths:
          - templates/fluxcd-helm
        output_type: yml
        output_path: gatekeeper/
        input_params:
          name: gatekeeper
          namespace: gatekeeper-system
          chart_name: gatekeeper
          chart_version: 3.5.1
          repository_name: gatekeeper-github-repo
          repository_url: https://open-policy-agent.github.io/gatekeeper/charts
          helm_values_files:
            - components/gatekeeper/${gatekeeper:version}/helm-values-files/common.yml