parameters:
  ingress_nginx_kind:
    version: v1
    manifest_version: controller-v0.47.0
  kapitan:
    dependencies:
      - type: https
        output_path: components/ingress-nginx-kind/deploy.yml
        source: https://raw.githubusercontent.com/kubernetes/ingress-nginx/${ingress_nginx_kind:manifest_version}/deploy/static/provider/kind/deploy.yaml
    compile:
      - name: copy-ingress-nginx-resources
        input_type: copy
        input_paths:
          - components/ingress-nginx-kind/
        output_type: yml
        output_path: ingress-nginx-kind/