apiVersion: source.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 10m
  url: https://open-policy-agent.github.io/gatekeeper/charts
