parameters:
  ingress_nginx:
    version: v1
  kapitan:
    compile:
      - name: template-ingress-nginx-namespace
        input_type: kadet
        input_paths:
          - templates/create-namespace
        output_type: yml
        output_path: ingress-nginx/
        input_params:
          name: ingress-nginx

      - name: template-ingress-nginx-fluxcd-resources
        input_type: kadet
        input_paths:
          - templates/fluxcd-helm
        output_type: yml
        output_path: ingress-nginx/
        input_params:
          name: ingress-nginx
          namespace: ingress-nginx
          chart_name: ingress-nginx
          chart_version: 3.34.0
          repository_name: ingress-nginx-github-repo
          repository_url: https://kubernetes.github.io/ingress-nginx
          helm_values_files:
            - components/ingress-nginx/${ingress_nginx:version}/helm-values-files/common.yml