apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: sock-shop-git-repository
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/microservices-demo/microservices-demo.git
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/kubernetes/manifests