apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sock-shop
  namespace: flux-system
spec:
  interval: 5m
  path: ./deploy/kubernetes/manifests/
  prune: true
  targetNamespace: sock-shop
  sourceRef:
    kind: GitRepository
    name: sock-shop-git-repository
  timeout: 2m