apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: NAME
  namespace: NAMESPACE
spec:
  releaseName: NAME
  chart:
    spec:
      chart: CHART_NAME
      version: CHART_VERSION
      sourceRef:
        kind: HelmRepository
        name: REPOSITORY_NAME
        namespace: NAMESPACE
  interval: 5m
  install:
    remediation:
      retries: 3
  values: {}