---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: compiled-dev
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./compiled/dev
  prune: false
  sourceRef:
    kind: GitRepository
    name: repo-root
