apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx-github-repo
  namespace: ingress-nginx
spec:
  interval: 10m
  url: https://kubernetes.github.io/ingress-nginx
